server:
  port: 8082

name: zhangsan

person:
  name: zhangsan
  score: 100
  age: 19

#person1: {name: zhangsan, score: 90}

city:
  - beijing
  - tianjing
  - shanghai

student:
  - name: zhangsan
    age: 25
    addr: shanghai
  - name: wangwu
    age: 27
    addr: guangdong

map:
  key1: value1
  key2: value2